#!/bin/bash
#
#SBATCH --job-name=S2_BIDS_CHOCO
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 2:00:00
#SBATCH --mem-per-cpu 80000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/error_files/bids_error_ses-2_%a_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/error_files/bids_error_ses-2_%a_err.txt

# assign correct variable name for "subject" from array id number  

if [ ${SLURM_ARRAY_TASK_ID} -lt 10 ]; then
    id="sub-00${SLURM_ARRAY_TASK_ID}"
elif [  ${SLURM_ARRAY_TASK_ID} -lt 100 ]; then
    id="sub-0${SLURM_ARRAY_TASK_ID}"
else 
    id="sub-${SLURM_ARRAY_TASK_ID}" 
fi
    
# export id value to python script
export id
#echo "$id" >> /projects/niblab/bids_projects/Experiments/ChocoData/error_files/my_output.txt
singularity exec -B /:/test /projects/niblab/bids_projects/Singularity_Containers/heudiconv.simg heudiconv -b -d /test/projects/niblab/data/{subject}/dicoms/wave1/dicoms/${in}/*IMA -s eric_data -f /test/projects/niblab/bids_projects/Heuristic_Files/choco_heuristic.py -c dcm2niix -o /test/projects/niblab/bids_projects/Experiments/ChocoData/BIDS/ses-1/${id}